---
platform: linux

inputs:
- name: time-resource
  path: gopath/src/github.com/concourse/time-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/concourse/time-resource/scripts/ci
