---
platform: linux
  type: docker-image
  source: {repository: 140.211.168.97:5000/golang:1.6}

inputs:
- name: time-resource
  path: gopath/src/github.com/concourse/time-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/concourse/time-resource/scripts/ci
